const i18nOptions = {
  locale: "sk",
  // fallbackLocale: "en",
  messages: {
    sk: {
      Menu: "Menu",
      AllProducts: "Všetky produkty",
      Back: "Späť",
      Search: "Hľadať",
      AllCategories: "Všetky kategorie",
      Price: "Cena",
      Anywhere: "Kdekoľvek",
      ctg_clothing: "Oblečenie",
      ctg_footwear: "Obuv",
      ctg_accessories: "Doplnky",
      ctg_shirts: "Tričká",
      ctg_tickets: "Lístky",
      ctg_festivals: "Festivaly",
      ctg_planeTickets: "Letenky",
      ctg_services: "Služby",
      ctg_tutoring: "Doučovanie",
      ctg_accomodation: "Ubytovanie",
      ctg_music: "Hudba",
      ctg_drums: "Bubny",
      ctg_guitar: "Gitary",
      ctg_keyboard: "Klávesy",
      ctg_pcPhone: "PC & Mobily",
      ctg_laptops: "Laptopy",
      ctg_pcKeyboard: "Klávesnice",
      ctg_mouse: "PC myši",
      ctg_furniture: "Nábytok",
      ctg_chairs: "Stoličky",
      ctg_tables: "Stoly",
      ctg_drawers: "Šuflíky",
      ctg_books: "Knihy",
      ctg_fiction: "Fikcia",
      ctg_historical: "Historické",
      ctg_textbooks: "Učebnice",
      ctg_homemade: "Domáce",
      ctg_electronics: "Elektronika",
      ctg_microwaves: "Mikrovlnky",
      ctg_refrigerators: "Chladničky",
      fltr_latest: "Najnovšie",
      fltr_oldest: "Najstaršie",
      fltr_minPrice: "Najmenšia cena",
      fltr_maxPrice: "Najvyššia cena",
      fltr_agreement: "Dohodou",
      fltr_offer: "Ponúkni",
      fltr_inText: "V popise",
      fltr_free: "Zadarmo",
      Logout: "Odhlásiť",
      Home: "Domov",
      Browse: "Prehľadávať",
      Favourites: "Obľúbené",
      MyProducts: "Moje produkty",
      Chat: "Chat",
      Login: "Prihlásiť",
      DoLogin: "Prihlásiť sa",
      SignUp: "Registrovať",
      DoSignUp: "Registrovať sa",
      AdminPanel: "Admin Panel",
      Notifications: "Upozornenia",
      CustomerService: "Zákaznický servis",
      Terms: "Podmienky",
      Collaboration: "Spolupráca",
      AboutUs: "O nás",
      DataPrivacy: "Súkromie údajov",
      FooterCopy: "Všetky práva vyhradené",
      MadeBy: "Vytvoril",
      AreYouSure: "Si si istý",
      Yes: "Áno",
      No: "Nie",
      Username: "Používateľské meno",
      Email: "Email",
      Password: "Heslo",
      RepeatPassword: "Heslo znova",
      AuthNoAccInfo: "Nemáš ešte účet?", // Don't have an account yet?
      AuthHasAccInfo: "Máš už účet?", // Already have an account?
      InvalidEmail: "Neplatný email",
      InvalidPassword: "Neplatné heslo",
      InvalidUsername: "Neplatné používateľské meno",
      PasswordsDontMatch: "Heslá sa nezhodujú",
      RegisterSuccess: "Registrácia prebehla úspešne",
      RegisterFailed: "Nepodarilo sa registrovať",
      LoginSuccess: "Prihlásenie prebehlo úspešne",
      LoginFailed: "Nepodarilo sa prihlásiť",
      BannerUserInfo: "Používateľ je zabanovaný, dôvod:",
      InvalidCredentials: "Nesprávne prihlasovacie údaje",
      ProductsSold: "Predané prodkty",
      SoldIn96hInfo: "produktov predaných za posledných 96h", //  products sold in last 96 hours
      FAQInfo: "často kladené otázky",
      NotiInfo: "zostante v obraze", // stay up to date
      LatestSoldProducts: "Najnovšie predané produkty",
      NoProductsFound: "Žiadne produkty neboli nájdené! :(", // No products were found! :(
      agreement: "Dohodou",
      offer: "Ponúkni",
      inText: "V popise",
      free: "Zadarmo",
      ProductTitle: "Názov produktu",
      Location: "Lokácia",
      Views: "Zobrazenia",
      Count: "Počet",
      Message: "Správa",
      Seller: "Predávajúci",
      Share: "Zdielať",
      Print: "Tlačiť",
      RateUser: "Ohodnotiť používateľa",
      ReportProduct: "Nahlásiť produkt",
      Rate: "Ohodnotiť",
      Cancel: "Zrušiť",
      RatingTitle: "Názov hodnotenia",
      Title: "Názov",
      RatedBy: "Hodnotené používateľom",
      SelectRating: "Vyber hodnotenie",
      RatedUser: "Hodnotený používateľ",
      RatedProduct: "Hodnotený produkt",
      Description: "Popis",
      User: "Používateľ",
      Product: "Produkt",
      ReportDescription: "Popis problému",
      Report: "Nahlásiť",
      ProductHistory: "História produktu",
      CreatedAt: "Vytvorené",
      SaleEnded: "Predaj skončil",
      NoHistoryInfo: "Tento produkt ešte nemal žiadne významenjšie zmeny!", // This product didn't have any significant changes made yet!
      View: "Zobraziť",
      Sold: "Predané",
      Added: "Pridané",
      ChangedPrice: "Zmena ceny",
      CountOfLeft: "Počet dostupných", // Count of available left
      EditProduct: "Upraviť produkt",
      CreateProduct: "Vytvoriť produkt",
      Preview: "Náhľad",
      Editor: "Úprava",
      Create: "Vytvoriť",
      Save: "Uložiť",
      Sales: "Predaje",
      Images: "Obrázky",
      Main: "Hlavný",
      AddImage: "Pridať obrázok",
      Category: "Kategória",
      SubCategory: "Podkategória",
      Or: "Alebo",
      SpecialPrice: "Špeciálna cena",
      SameAddressInfo: "Použiť rovnakú adresu ako na profile", // Use the same address as your account
      Address: "Adresa",
      Dorm: "Internát",
      NoSalesInfo: "Tento produkt ešte nebol predaný!", // This product doesn't have any sales yet! :(
      Bought: "Kúpil/a",
      Buyer: "Kupujúci",
      Add: "Pridať",
      EditSale: "Upraviť predaj",
      AddSale: "Predať",
      JoinedOn: "Registrovaný/a",
      Rating: "Hodnotenie",
      Products: "Produkty",
      OnSale: "na predaj",
      Ratings: "Hodnotenia",
      ReportUser: "Nahlásiť používateľa",
      onSale: "Na predaj",
      saleEnded: "Predaj skončil",
      self: "Vlastné",
      others: "Ostatné",
      PhoneNumber: "Tel. číslo",
      UserSettings: "Nastavenia požívateľa",
      CisloPlaceholder: "tel. číslo",
      HladajKrajinu: "hľadaj krajinu",
      System: "Systém",
      Messages: "Správy",
      Confirm: "Potvrdiť",
      NoNotiInfo: "Žiadne notifikácie na zobrazenie!", // Seems like there are no notifications for you yet!
      Requests: "Žiadosti",
      NoReqInfo: "Žiadne žiadosti!", // No requests yet!
      Known: "Známe",
      You: "Ty",
      SoEmpty: "... tak prázdno :(", // ... so empty :(
      NoMsgsInfo1: "Zatiaľ tu nie sú žiadne správy!", // Seems like there are no messages yet!  
      NoMsgsInfo2: "Buď prvý čo sa ozve s pozdravom :)", // Be the first one to say hi :)
      SelectChatInfo: "Zvoľ si používateľa pre posielanie a zobrazovanie správ", // Select a chat to send & view messages
      AcceptReqInfo: "Prijmi túto žiadosť aby si mohol písať", // Accept this request to start messaging with user
      Accept: "Prijať",
      AddUserToChat: "Pridať používateľa do chatu",
      
    },
    en: {
      Menu: "Menu",
      AllProducts: "All products",
      Back: "Back"
    },
  },
};

export { i18nOptions };
