const i18nOptions = {
  locale: "sk",
  // fallbackLocale: "en",
  messages: {
    sk: {
      Menu: "Menu",
      AllProducts: "Všetky produkty",
      Back: "Späť",
      Search: "Hľadať",
      AllCategories: "Všetky kategorie",
      Price: "Cena",
      Anywhere: "Kdekoľvek",
      ctg_clothing: "Oblečenie",
      ctg_footwear: "Obuv",
      ctg_accessories: "Doplnky",
      ctg_shirts: "Tričká",
      ctg_tickets: "Lístky",
      ctg_festivals: "Festivaly",
      ctg_planeTickets: "Letenky",
      ctg_services: "Služby",
      ctg_tutoring: "Doučovanie",
      ctg_accomodation: "Ubytovanie",
      ctg_music: "Hudba",
      ctg_drums: "Bubny",
      ctg_guitar: "Gitary",
      ctg_keyboard: "Klávesy",
      ctg_pcPhone: "PC & Mobily",
      ctg_laptops: "Laptopy",
      ctg_pcKeyboard: "Klávesnice",
      ctg_mouse: "PC myši",
      ctg_furniture: "Nábytok",
      ctg_chairs: "Stoličky",
      ctg_tables: "Stoly",
      ctg_drawers: "Šuflíky",
      ctg_books: "Knihy",
      ctg_fiction: "Fikcia",
      ctg_historical: "Historické",
      ctg_textbooks: "Učebnice",
      ctg_homemade: "Domáce",
      ctg_electronics: "Elektronika",
      ctg_microwaves: "Mikrovlnky",
      ctg_refrigerators: "Chladničky",
      ctg_allProducts: "Všetky produkty",
      fltr_latest: "Najnovšie",
      fltr_oldest: "Najstaršie",
      fltr_minPrice: "Najmenšia cena",
      fltr_maxPrice: "Najvyššia cena",
      fltr_agreement: "Dohodou",
      fltr_offer: "Ponúkni",
      fltr_inText: "V popise",
      fltr_free: "Zadarmo",
      fltr_userId: "ID používateľa",
      fltr_maxRating: "Najväčšie hodnotenie",
      fltr_minRating: "Najmenšie hodnotenie",
      fltr_maxProductsOnSale: "Najviac prod. v predaji",
      fltr_maxProductsSold: "Najviac predaných prod.",
      fltr_maxProductsBought: "Najviac kúpených prod.",
      fltr_maxOwnReports: "Najviac vlastných nahlásení",
      fltr_maxOthersReports: "Najviac nahlásení ostatných",
      Logout: "Odhlásiť",
      Home: "Domov",
      Browse: "Prehľadávať",
      Favourites: "Obľúbené",
      MyProducts: "Moje produkty",
      Chat: "Chat",
      Login: "Prihlásiť",
      DoLogin: "Prihlásiť sa",
      SignUp: "Registrovať",
      DoSignUp: "Registrovať sa",
      AdminPanel: "Admin Panel",
      Notifications: "Upozornenia",
      CustomerService: "Zákaznický servis",
      Terms: "Podmienky",
      Collaboration: "Spolupráca",
      AboutUs: "O nás",
      DataPrivacy: "Súkromie údajov",
      FooterCopy: "Všetky práva vyhradené",
      MadeBy: "Vytvoril",
      AreYouSure: "Si si istý",
      Yes: "Áno",
      No: "Nie",
      Username: "Používateľské meno",
      Email: "Email",
      Password: "Heslo",
      RepeatPassword: "Heslo znova",
      AuthNoAccInfo: "Nemáš ešte účet?",
      AuthHasAccInfo: "Máš už účet?",
      InvalidEmail: "Neplatný email",
      InvalidPassword: "Neplatné heslo",
      InvalidUsername: "Neplatné používateľské meno",
      PasswordsDontMatch: "Heslá sa nezhodujú",
      RegisterSuccess: "Registrácia prebehla úspešne",
      RegisterFailed: "Nepodarilo sa registrovať",
      LoginSuccess: "Prihlásenie prebehlo úspešne",
      LoginFailed: "Nepodarilo sa prihlásiť",
      BannerUserInfo: "Používateľ je zabanovaný, dôvod:",
      InvalidCredentials: "Nesprávne prihlasovacie údaje",
      ProductsSold: "Predané prodkty",
      SoldIn96hInfo: "produktov predaných za posledných 96h",
      FAQInfo: "často kladené otázky",
      NotiInfo: "zostante v obraze",
      LatestSoldProducts: "Najnovšie predané produkty",
      NoProductsFound: "Žiadne produkty neboli nájdené! :(",
      agreement: "Dohodou",
      offer: "Ponúkni",
      inText: "V popise",
      free: "Zadarmo",
      ProductTitle: "Názov produktu",
      Location: "Lokácia",
      Views: "Zobrazenia",
      Count: "Počet",
      Message: "Správa",
      Seller: "Predávajúci",
      Share: "Zdielať",
      Print: "Tlačiť",
      RateUser: "Ohodnotiť používateľa",
      ReportProduct: "Nahlásiť produkt",
      Rate: "Ohodnotiť",
      Cancel: "Zrušiť",
      RatingTitle: "Názov hodnotenia",
      Title: "Názov",
      RatedBy: "Hodnotené používateľom",
      SelectRating: "Vyber hodnotenie",
      RatedUser: "Hodnotený používateľ",
      RatedProduct: "Hodnotený produkt",
      Description: "Popis",
      User: "Používateľ",
      Product: "Produkt",
      ReportDescription: "Popis problému",
      Report: "Nahlásiť",
      ProductHistory: "História produktu",
      CreatedAt: "Vytvorené",
      SaleEnded: "Predaj skončil",
      NoHistoryInfo: "Tento produkt ešte nemal žiadne významenjšie zmeny!",
      View: "Zobraziť",
      Sold: "Predané",
      Added: "Pridané",
      ChangedPrice: "Zmena ceny",
      CountOfLeft: "Počet dostupných",
      EditProduct: "Upraviť produkt",
      CreateProduct: "Vytvoriť produkt",
      Preview: "Náhľad",
      Editor: "Úprava",
      Create: "Vytvoriť",
      Save: "Uložiť",
      Sales: "Predaje",
      Images: "Obrázky",
      Main: "Hlavný",
      AddImage: "Pridať obrázok",
      Category: "Kategória",
      SubCategory: "Podkategória",
      Or: "Alebo",
      SpecialPrice: "Špeciálna cena",
      SameAddressInfo: "Použiť rovnakú adresu ako na profile",
      Address: "Adresa",
      Dorm: "Internát",
      NoSalesInfo: "Tento produkt ešte nebol predaný!",
      Bought: "Kúpil/a",
      Buyer: "Kupujúci",
      Add: "Pridať",
      EditSale: "Upraviť predaj",
      AddSale: "Predať",
      JoinedOn: "Registrovaný/a",
      Rating: "Hodnotenie",
      Products: "Produkty",
      OnSale: "na predaj",
      Ratings: "Hodnotenia",
      ReportUser: "Nahlásiť používateľa",
      onSale: "Na predaj",
      saleEnded: "Predaj skončil",
      self: "Vlastné",
      others: "Ostatné",
      PhoneNumber: "Tel. číslo",
      UserSettings: "Nastavenia požívateľa",
      CisloPlaceholder: "tel. číslo",
      HladajKrajinu: "hľadaj krajinu",
      System: "Systém",
      Messages: "Správy",
      Confirm: "Potvrdiť",
      NoNotiInfo: "Žiadne notifikácie na zobrazenie!",
      Requests: "Žiadosti",
      NoReqInfo: "Žiadne žiadosti!",
      Known: "Známe",
      You: "Ty",
      SoEmpty: "... tak prázdno :(",
      NoMsgsInfo1: "Zatiaľ tu nie sú žiadne správy!", 
      NoMsgsInfo2: "Buď prvý čo sa ozve s pozdravom :)",
      SelectChatInfo: "Zvoľ si používateľa pre posielanie a zobrazovanie správ",
      AcceptReqInfo: "Prijmi túto žiadosť aby si mohol písať",
      Accept: "Prijať",
      AddUserToChat: "Pridať používateľa do chatu",
      Users: "Používatelia",
      Reports: "Nahlásenia",
      all: "Všetko",
      users: "Používatelia",
      products: "Produkty",
      confirmed: "Potvrdené",
      unconfirmed: "Nepotvrdené",
      active: "Aktívny",
      banned: "Banned",
      Rated: "Hodnotil/a",
      Others: "ostatných",
      Own: "vlastné",
      Ban: "Ban",
      Edit: "Upraviť",
      UserAdminEditInfo1: "Ostatné nastavenia sú priamo v",
      UserAdminEditInfo2: "požívateľskom profile",
      DelAvatarInfo: "Vymazať profilovku",
      IsSaleConfInfo: "Je predaj potvrdený",
      InvalidEmail: "Neplatný alebo nesprávny email!",
      InvalidPassword: "Nesprávne heslo!",
      InvalidUsername: "Nesprávne meno!",
      PasswordsDontMatch: "Hesla sa nezhodujú!",
      RegisterSuccess: "Registrácia bola úspešná, prihláste sa",
      RegisterFailed: "Nepodarilo sa registrovať!",
      LoginSuccess: "Prihlásenie bolo úspešné",
      LoginFailed: "Nepodarilo sa prihlásiť!",
      BannedUserInfo: "Používateľ je zabanovaný, dôvod: ",
      InvalidCredentials: "Nesprávne prihlasovacie údaje!",
      LocationGetFailed: "Nepodarilo sa získať polohu!",
      BrowserGeoUnsupported: "Prehliadač nepodporuje získanie polohy!",
      LogoutSuccess: "Odhlásenie prebehlo úspešne",
      LogoutFailed: "Nepodarilo sa odhlásiť",
      InvalidItemToEdit: "Nesprávna vec na upravenie!",
      ItemEditSuccess: "Upravenie prebehlo úspešne",
      ItemEditFailed: "Nepodarilo sa upraviť danú vec!",
      InvalidItemToDelete: "Nesprávna vec na vymazanie!",
      ItemDeleteSuccess: "Vymazanie prebehlo úspešnie",
      ItemDeleteFailed: "Nepodarilo sa vymazať danú vec!",
      ConfirmReportSuccess: "Potvrdenie nahlásenia prebehlo úspešne",
      ConfirmReportFailed: "Nepodarilo sa potvrdiť nahlásenie!",
      InvalidDescription: "Nesprávny popis!",
      ReportAddSuccess: "Nahlásenie bolo úspešne vytvorené",
      ReportAddFailed: "Nahlásenie sa nepodarilo!",
      BookmarkRemoveSuccess: "Produkt bol úspešne odstránený z obľúbených",
      BookmarkRemoveFailed: "Nepodarilo sa odstrániť produkt z obľúbených!",
      InvalidSelectedUserToAddChat: "Neplatný používateľ na pridanie do chatu!",
      ConfirmSaleSuccess: "Predaj bol potvrdený úspešne",
      ConfirmSaleFailed: "Nepodarilo sa potrvdiť predaj!",
      BookmarkAddSuccess: "Produkt bol pridaný do obľúbených",
      BookmarkAddFailed: "Nepodarilo sa pridať produkt k obľúbeným!",
      ProductDeleteSuccess: "Produkt bol odstránený úspešne",
      ProductDeleteFailed: "Nepodarilo sa odstrániť produkt!",
      FailedToOpenChatWithUser: "Nepodarilo sa otvoriť chat s používateľom!",
      PhoneCopySuccess: "Telefónne číslo bolo skopírované úspešne",
      PhoneCopyFailed: "Nepodarilo sa skopírovať telefónne číslo!",
      InvalidProductTitle: "Neplatný názov produktu!",
      InvalidProductMainCategory: "Neplatná hlavná kategória produktu!",
      InvalidProductPrice: "Neplatná cena produktu!",
      InvalidProductAddress: "Neplatná adresa pre produkt!",
      InvalidProductCount: "Neplatný počet kusov produktu!",
      ProductEditSuccess: "Produkt bol upravený úspešne",
      ProductEditFailed: "Nepodarilo sa upraviť produkt!",
      ProductAddSuccess: "Produkt bol priadný úspešne",
      ProductAddFailed: "Nepodarilo sa pridať produkt!",
      SaleAddSuccess: "Predaj bol uskutočnený úspešne",
      SaleAddFailed: "Nepodarilo sa uskutočniť predaj!",
      MissingRatingTitle: "Chýba názov hodnotenia!",
      RatedUserSuccess: "Používateľ bol ohodnotený úspešne",
      RatedUserFailed: "Nepodarilo sa ohodnotiť používateľa!",
      PleaseSelectFile: "Prosím vyberte súbor",
      SavedAvatarSuccess: "Nahratie profilovej foto bolo úspešné",
      SavedAvatarFailed: "Nepodarilo sa nahrať profilovú foto!",
      InvalidPhoneNumber: "Neplatné telefónne číslo!",
      NothingToSave: "Nič nebolo zmenené na uloženie!",
      UpdateUserSettingsSuccess: "Zmena nastavení bola úspešná",
      UpdateUserSettingsFailed: "Nepodarilo sa zmeniť nastavenia!",
      UserBanSuccess: "Používateľ bol úspešne zabanovaný",
      UserBanFailed: "Nepodarilo sa zabanovať používateľa!",
      EndSaleOn0CountInfo: "Ukončenie predaja keď počet produktu klesne na 0",
      EndSale: "Ukončiť predaj",
      EndSaleSuccess: "Predaj produktu bol ukončený úspešne",
      EndSaleFailed: "Nepodarilo sa ukončiť predaj produktu!",
      ConfirmEndSaleInfo: "O ukončení predaja tohto produktu?",
      SaleEndedAt: "Predaj ukončený",
      Dormitory: "Internát",
      FAQ1_title: "Ako funguje predávanie produktov?",
      FAQ1_answer1: 'Predávanie viete uskutočňovať sami vy, ako predávajúci daného produktu - stačí prejsť do úprav produktu (ikonka ceruzky pri zobrazenom produkte), a tam prejsť do sekcie "Predaje" buď rolovaním dole alebo kliknutím tlačidla "Predaje" hneď hore.',
      FAQ1_answer2: 'Kliknutím na + ikonku sa vám otvorí okno, kde už môžete vytvoriť predaj - buď na zaregistrovaného zákazníka alebo na neznámeho (nevyberiete si žiadneho)',
      FAQ1_answer3: 'V oboch prípadoch je predaj už vytvorený, ale v prípade zvolenia existujúceho zákazníka ho ešte musí daný zákazník potvrdiť.',
      FAQ1_answer4: 'Ak je zákazník neexistujúci, tak predaj je potvrdený automaticky.',
      FAQ2_title: "Čo znamená ukončenie predaju pri produktoch?",
      FAQ2_answer1: 'Predaj produktu bol ukončený a nedá sa uskutočňovať nové predaje - táto situácia nastáva v 2 možnostiach:',
      FAQ2_answer2: 'Predaj bol ukončený automaticky keď sa počet kusov produktu dostal na 0 - to platí len ak to je nastavené pre daný produkt, automaticky to je vypnuté.',
      FAQ2_answer3: 'Ak to nie je nastavené, tak po klesnutí počtu kusov na 0 sa po 72h skončí predaj ak dovtedy stále nebudú voľné produkty na predaj (počet bude stále rovný 0)',
      FAQ3_title: "Ako funguje kupovanie produktov?",
      FAQ3_answer1: 'Kupovanie sa vykonáva jednoducho kontaktovaním vlastníka produktu - buď telefonicky ak má zverejnené tel. číslo, alebo správou cez chat - vtedy ale musíte byť prihláseny aby ste mohli posielať správy',
      FAQ3_answer2: 'V prípade ak nemáte učet tak predávajúci nemusí nikoho uviesť, stačí sa len dohodnúť. Predaj a kúpa sa potvrdí automaticky.',
      FAQ3_answer3: 'V opačnom prípade potrebujete potvrdiť kúpu produktu v "Upozornenia" (odkaz je v bočnom menu). Po potvrdení bol predaj overený.',
      FAQ4_title: "Ako funguje počet pri produktoch?",
      FAQ4_answer1: 'Produkty môžu mať viaceré kusy na predaj - predávať/kupovať sa stále da len 1 alebo viacero naraz.',
      FAQ4_answer2: 'Počet je v podstate neobmedzený, dá sa stále navyšovať - ľahké doplnenie zásob.',
      FAQ4_answer3: 'Pre viac info o počte kusov si pozrite otázku "Čo znamená ukončenie predaju pri produktoch?"',
      FAQ5_title: "Čo ak mám problém s používateľom alebo produktom?",
      FAQ5_answer1: 'V prípade akéhokoľvek problému s používateľom alebo produktom je možné spraviť nahlásenie, kde svoj problém popíšete. Naši administrátori problémy čo najrýchlejšie vyriešia.',
      FAQ5_answer2: 'Ak to bude vhodné, tak dostanete správu od administrátora o vyriešení problému.',
      LoginInfo: "Prihlás sa na používanie všetkých možností",
      MainInfo: "Hlavné informácie"
    },
    en: {
      Menu: "Menu",
      AllProducts: "All products",
      Back: "Back",
      Search: "Search",
      AllCategories: "All categories",
      Price: "Price",
      Anywhere: "Anywhere",
      ctg_clothing: "Clothing",
      ctg_footwear: "Footwear",
      ctg_accessories: "Accessories",
      ctg_shirts: "Shirts",
      ctg_tickets: "Tickets",
      ctg_festivals: "Festivals",
      ctg_planeTickets: "Plane tickets",
      ctg_services: "Services",
      ctg_tutoring: "Tutoring",
      ctg_accomodation: "Accomodation",
      ctg_music: "Music",
      ctg_drums: "Drums",
      ctg_guitar: "Guitars",
      ctg_keyboard: "Keyboard",
      ctg_pcPhone: "PC & phone",
      ctg_laptops: "Laptops",
      ctg_pcKeyboard: "Keyboards",
      ctg_mouse: "PC mouses",
      ctg_furniture: "Furniture",
      ctg_chairs: "Chairs",
      ctg_tables: "Tables",
      ctg_drawers: "Drawers",
      ctg_books: "Books",
      ctg_fiction: "Fiction",
      ctg_historical: "Historical",
      ctg_textbooks: "Textbooks",
      ctg_homemade: "Homemade",
      ctg_electronics: "Electronics",
      ctg_microwaves: "Microwaves",
      ctg_refrigerators: "Refrigerators",
      ctg_allProducts: "All products",
      fltr_latest: "Latest",
      fltr_oldest: "Oldest",
      fltr_minPrice: "Smallest price",
      fltr_maxPrice: "Highest price",
      fltr_agreement: "Agreement",
      fltr_offer: "Offer",
      fltr_inText: "In text",
      fltr_free: "Free",
      fltr_userId: "User ID",
      fltr_maxRating: "Biggest ratings",
      fltr_minRating: "Smallest ratings",
      fltr_maxProductsOnSale: "Most products on sale",
      fltr_maxProductsSold: "Most sold products",
      fltr_maxProductsBought: "Most bought products",
      fltr_maxOwnReports: "Most own reports",
      fltr_maxOthersReports: "Most others reports",
      Logout: "Logout",
      Home: "Home",
      Browse: "Browse",
      Favourites: "Favourites",
      MyProducts: "My products",
      Chat: "Chat",
      Login: "Login",
      DoLogin: "Login",
      SignUp: "Sign up",
      DoSignUp: "Sign up",
      AdminPanel: "Admin Panel",
      Notifications: "Notifications",
      CustomerService: "Customer service",
      Terms: "Terms",
      Collaboration: "Collaboration",
      AboutUs: "About us",
      DataPrivacy: "Data privacy",
      FooterCopy: "All rights reserved",
      MadeBy: "Made by",
      AreYouSure: "Are you sure",
      Yes: "Yes",
      No: "No",
      Username: "Username",
      Email: "Email",
      Password: "Password",
      RepeatPassword: "Password again",
      AuthNoAccInfo: "Don't have an account yet?",
      AuthHasAccInfo: "Already have an account?",
      InvalidEmail: "Invalid email",
      InvalidPassword: "Invalid password",
      InvalidUsername: "Invalid username",
      PasswordsDontMatch: "Passwords do not match",
      RegisterSuccess: "Registered successfully",
      RegisterFailed: "Failed to register",
      LoginSuccess: "Login was successfull",
      LoginFailed: "Failed to login",
      BannerUserInfo: "User is banned, reason:",
      InvalidCredentials: "Invalid login credentials",
      ProductsSold: "Products sold",
      SoldIn96hInfo: "products sold in last 96 hours", 
      FAQInfo: "frequently asked questions",
      NotiInfo: "stay up to date",
      LatestSoldProducts: "Latest sold products",
      NoProductsFound: "No products were found! :(",
      agreement: "Agreement",
      offer: "Offer",
      inText: "In text",
      free: "Free",
      ProductTitle: "Product title",
      Location: "Location",
      Views: "Views",
      Count: "Count",
      Message: "Message",
      Seller: "Seller",
      Share: "Share",
      Print: "Print",
      RateUser: "Rate User",
      ReportProduct: "Report Product",
      Rate: "Rate",
      Cancel: "Cancel",
      RatingTitle: "Rating title",
      Title: "Title",
      RatedBy: "Rated by",
      SelectRating: "select rating",
      RatedUser: "Rated user",
      RatedProduct: "Rated product",
      Description: "Description",
      User: "User",
      Product: "Product",
      ReportDescription: "Problem description",
      Report: "Report",
      ProductHistory: "Product history",
      CreatedAt: "Created at",
      SaleEnded: "Sale ended",
      NoHistoryInfo: "This product didn't have any significant changes made yet!",
      View: "View",
      Sold: "Sold",
      Added: "Added",
      ChangedPrice: "Changed price",
      CountOfLeft: "Count of available left",
      EditProduct: "Edit product",
      CreateProduct: "Create product",
      Preview: "Preview",
      Editor: "Editor",
      Create: "Create",
      Save: "Save",
      Sales: "Sales",
      Images: "Images",
      Main: "Main",
      AddImage: "Add image",
      Category: "Category",
      SubCategory: "Subcategory",
      Or: "Or",
      SpecialPrice: "Special price",
      SameAddressInfo: "Use the same address as your account",
      Address: "Address",
      Dorm: "Dorm",
      NoSalesInfo: "This product doesn't have any sales yet! :(",
      Bought: "Bought",
      Buyer: "Buyer",
      Add: "Add",
      EditSale: "Edit sale",
      AddSale: "Add sale",
      JoinedOn: "Joined on",
      Rating: "Rating",
      Products: "Products",
      OnSale: "on sale",
      Ratings: "Ratings",
      ReportUser: "Report user",
      onSale: "on sale",
      saleEnded: "Sale ended",
      self: "Self",
      others: "Others",
      PhoneNumber: "Phone number",
      UserSettings: "User settings",
      CisloPlaceholder: "Phone number",
      HladajKrajinu: "search country",
      System: "System",
      Messages: "Messages",
      Confirm: "Confirm",
      NoNotiInfo: "Seems like there are no notifications for you yet!",
      Requests: "Requests",
      NoReqInfo: "No requests yet!",
      Known: "Known",
      You: "You",
      SoEmpty: "... so empty :(",
      NoMsgsInfo1: "Seems like there are no messages yet!",
      NoMsgsInfo2: "Be the first one to say hi :)",
      SelectChatInfo: "Select a chat to send & view messages", 
      AcceptReqInfo: "Accept this request to start messaging with user",
      Accept: "Accept",
      AddUserToChat: "Add user to chat",
      Users: "Users",
      Reports: "Reports",
      all: "All",
      users: "Users",
      products: "Products",
      confirmed: "Confirmed",
      unconfirmed: "Unconfirmed",
      active: "Active",
      banned: "Banned",
      Rated: "Rated",
      Others: "Others",
      Own: "Own",
      Ban: "Ban",
      Edit: "Edit",
      UserAdminEditInfo1: "Other settings are available directly in ",
      UserAdminEditInfo2: "user profile",
      DelAvatarInfo: "Delete user avatar",
      IsSaleConfInfo: "Is sale confirmed",
      InvalidEmail: "Invalid or incorrect email!",
      InvalidPassword: "Invalid password!",
      InvalidUsername: "Invalid name!",
      PasswordsDontMatch: "Passwords don't match!",
      RegisterSuccess: "Registration was successfull, please login",
      RegisterFailed: "Failed to register!",
      LoginSuccess: "Login was successfull",
      LoginFailed: "Failed to login!",
      BannedUserInfo: "User is banned, reason: ",
      InvalidCredentials: "Invalid login credentials!",
      LocationGetFailed: "Failed to get position!",
      BrowserGeoUnsupported: "This browser doesn't support geo location!",
      LogoutSuccess: "Logged out successfully",
      LogoutFailed: "Failed to logout",
      InvalidItemToEdit: "Invalid item to edit!",
      ItemEditSuccess: "Item edit was successfull",
      ItemEditFailed: "Failed to edit item!",
      InvalidItemToDelete: "Invalid item to delete!",
      ItemDeleteSuccess: "Item delete was successfull!",
      ItemDeleteFailed: "Failed to delete item!",
      ConfirmReportSuccess: "Report was confirmed successfully",
      ConfirmReportFailed: "Failed to confirm report!",
      InvalidDescription: "Invalid description!",
      ReportAddSuccess: "Report was created successfully",
      ReportAddFailed: "Failed to create report!",
      BookmarkRemoveSuccess: "Product was removed from favourites successfully",
      BookmarkRemoveFailed: "Failed to remove product from favourites!",
      InvalidSelectedUserToAddChat: "Invalid user to add to chat!",
      ConfirmSaleSuccess: "Sale was confirmed successfully",
      ConfirmSaleFailed: "Failed to confirm sale!",
      BookmarkAddSuccess: "Product was added to favourites successfully",
      BookmarkAddFailed: "Failed to add product to favourites!",
      ProductDeleteSuccess: "Product was delete successfully",
      ProductDeleteFailed: "Failed to delete product!",
      FailedToOpenChatWithUser: "Failed to open chat with user!",
      PhoneCopySuccess: "Phone number was copied successfuly",
      PhoneCopyFailed: "Failed to copy phone number!",
      InvalidProductTitle: "Invalid product title!",
      InvalidProductMainCategory: "Invalid product main category!",
      InvalidProductPrice: "Invalid product price!",
      InvalidProductAddress: "Invalid address for product!",
      InvalidProductCount: "Invalid product count!",
      ProductEditSuccess: "Product was edited successfully!",
      ProductEditFailed: "Failed to edit product!",
      ProductAddSuccess: "Product was added successfully",
      ProductAddFailed: "Failed to add product!",
      SaleAddSuccess: "Sale was added succesfully!",
      SaleAddFailed: "Failed to add sale!",
      MissingRatingTitle: "Rating is missing a title!",
      RatedUserSuccess: "User was rated successfully",
      RatedUserFailed: "Failed to rate user!",
      PleaseSelectFile: "Please select a file",
      SavedAvatarSuccess: "User avatar upload was successfull",
      SavedAvatarFailed: "Failed to upload user avatar!",
      InvalidPhoneNumber: "Invalid phone number!",
      NothingToSave: "Nothing was changed to save!",
      UpdateUserSettingsSuccess: "User settings changes were successfull",
      UpdateUserSettingsFailed: "Failed to update user settings!",
      UserBanSuccess: "User was banned successfully",
      UserBanFailed: "Failed to ban user!",
      EndSaleOn0CountInfo: "End sale automatically when count reaches 0",
      EndSale: "End sale",
      EndSaleSuccess: "Ended product sale successfully",
      EndSaleFailed: "Failed to end product sale!",
      ConfirmEndSaleInfo: "About ending sale of this product?",
      SaleEndedAt: "Sale ended at",
      Dormitory: "Dormitory",
      FAQ1_title: "How does selling products work?",
      FAQ1_answer1: 'You can add sales as product seller/owner - all you need to do is go to product editor (pencil icon in shown product) and there navigate to "Sales" either by scrolling down or clicking button "Sales" right at the top.',
      FAQ1_answer2: 'Clicking the + icon a modal window will open, where you can add a sale - either for a registered user or as unknown (do not select any user)',
      FAQ1_answer3: 'In both cases the sale is finished, but if you chose an existing user, that user has to confirm that he really bought it.',
      FAQ1_answer4: 'If the buyer is unknown, the sale is confirmed automatically.',
      FAQ2_title: 'What does it mean when product has "sale ended"?',
      FAQ2_answer1: 'The sale of product is over and product cannot bet sold anymore - this situation happens in 2 scenarios:',
      FAQ2_answer2: 'The sale was ended automatically when product count reached 0 - this is only true if it is set in product options, its disabled by default.',
      FAQ2_answer3: 'If its not enabled, then when count reaches 0, a check will be performed after 72h if product count is still 0, then the sale will be over at that time.',
      FAQ3_title: "How does buying products work?",
      FAQ3_answer1: 'Buying products is simply done by contacting the seller - by telephone if it is public or by chat - sending a message, but in this case, you have to be logged in.',
      FAQ3_answer2: 'If you do not have an account, the seller does not have to set a buyer, agreement is enough. Sale will be confirmed automatically.',
      FAQ3_answer3: 'Otherwise, you as a buyer, need to confirm the sale in "Notifications" (link is in sidebar menu). After confirming, the sale is verified.',
      FAQ4_title: "How does product count work?",
      FAQ4_answer1: 'Products can have multiple pieces for sale - selling/buying can be still done for only 1 piece or many at once.',
      FAQ4_answer2: 'Count is basically unlimited, it can always be increased - easily restock.',
      FAQ4_answer3: 'For more infou about product count, find question "What does it mean when product has "sale ended"?"',
      FAQ5_title: "What if there's a problem with a user/product?",
      FAQ5_answer1: 'In case of any problem with a user or a product, you can report it and describe your problem. Our administrators will solve problems as fast as they can.',
      FAQ5_answer2: 'If appropiate, you will get a message from an administrator about solving your problem.',
      LoginInfo: "Login to use all features",
      MainInfo: "Main info"
    },
  },
};

export { i18nOptions };
