const i18nOptions = {
  locale: "sk",
  // fallbackLocale: "en",
  messages: {
    sk: {
      Menu: "Menu",
      AllProducts: "Všetky produkty",
      Back: "Späť",
      Search: "Hľadať",
      AllCategories: "Všetky kategorie",
      Price: "Cena",
      Anywhere: "Kdekoľvek",
      ctg_clothing: "Oblečenie",
      ctg_footwear: "Obuv",
      ctg_accessories: "Doplnky",
      ctg_shirts: "Tričká",
      ctg_tickets: "Lístky",
      ctg_festivals: "Festivaly",
      ctg_planeTickets: "Letenky",
      ctg_services: "Služby",
      ctg_tutoring: "Doučovanie",
      ctg_accomodation: "Ubytovanie",
      ctg_music: "Hudba",
      ctg_drums: "Bubny",
      ctg_guitar: "Gitary",
      ctg_keyboard: "Klávesy",
      ctg_pcPhone: "PC & Mobily",
      ctg_laptops: "Laptopy",
      ctg_pcKeyboard: "Klávesnice",
      ctg_mouse: "PC myši",
      ctg_furniture: "Nábytok",
      ctg_chairs: "Stoličky",
      ctg_tables: "Stoly",
      ctg_drawers: "Šuflíky",
      ctg_books: "Knihy",
      ctg_fiction: "Fikcia",
      ctg_historical: "Historické",
      ctg_textbooks: "Učebnice",
      ctg_homemade: "Domáce",
      ctg_electronics: "Elektronika",
      ctg_microwaves: "Mikrovlnky",
      ctg_refrigerators: "Chladničky",
      fltr_latest: "Najnovšie",
      fltr_oldest: "Najstaršie",
      fltr_minPrice: "Najmenšia cena",
      fltr_maxPrice: "Najvyššia cena",
      fltr_agreement: "Dohodou",
      fltr_offer: "Ponúkni",
      fltr_inText: "V popise",
      fltr_free: "Zadarmo",
      fltr_userId: "ID používateľa",
      fltr_maxRating: "Najväčšie hodnotenie",
      fltr_minRating: "Najmenšie hodnotenie",
      fltr_maxProductsOnSale: "Najviac prod. v predaji",
      fltr_maxProductsSold: "Najviac predaných prod.",
      fltr_maxProductsBought: "Najviac kúpených prod.",
      fltr_maxOwnReports: "Najviac vlastných nahlásení",
      fltr_maxOthersReports: "Najviac nahlásení ostatných",
      Logout: "Odhlásiť",
      Home: "Domov",
      Browse: "Prehľadávať",
      Favourites: "Obľúbené",
      MyProducts: "Moje produkty",
      Chat: "Chat",
      Login: "Prihlásiť",
      DoLogin: "Prihlásiť sa",
      SignUp: "Registrovať",
      DoSignUp: "Registrovať sa",
      AdminPanel: "Admin Panel",
      Notifications: "Upozornenia",
      CustomerService: "Zákaznický servis",
      Terms: "Podmienky",
      Collaboration: "Spolupráca",
      AboutUs: "O nás",
      DataPrivacy: "Súkromie údajov",
      FooterCopy: "Všetky práva vyhradené",
      MadeBy: "Vytvoril",
      AreYouSure: "Si si istý",
      Yes: "Áno",
      No: "Nie",
      Username: "Používateľské meno",
      Email: "Email",
      Password: "Heslo",
      RepeatPassword: "Heslo znova",
      AuthNoAccInfo: "Nemáš ešte účet?", // Don't have an account yet?
      AuthHasAccInfo: "Máš už účet?", // Already have an account?
      InvalidEmail: "Neplatný email",
      InvalidPassword: "Neplatné heslo",
      InvalidUsername: "Neplatné používateľské meno",
      PasswordsDontMatch: "Heslá sa nezhodujú",
      RegisterSuccess: "Registrácia prebehla úspešne",
      RegisterFailed: "Nepodarilo sa registrovať",
      LoginSuccess: "Prihlásenie prebehlo úspešne",
      LoginFailed: "Nepodarilo sa prihlásiť",
      BannerUserInfo: "Používateľ je zabanovaný, dôvod:",
      InvalidCredentials: "Nesprávne prihlasovacie údaje",
      ProductsSold: "Predané prodkty",
      SoldIn96hInfo: "produktov predaných za posledných 96h", //  products sold in last 96 hours
      FAQInfo: "často kladené otázky",
      NotiInfo: "zostante v obraze", // stay up to date
      LatestSoldProducts: "Najnovšie predané produkty",
      NoProductsFound: "Žiadne produkty neboli nájdené! :(", // No products were found! :(
      agreement: "Dohodou",
      offer: "Ponúkni",
      inText: "V popise",
      free: "Zadarmo",
      ProductTitle: "Názov produktu",
      Location: "Lokácia",
      Views: "Zobrazenia",
      Count: "Počet",
      Message: "Správa",
      Seller: "Predávajúci",
      Share: "Zdielať",
      Print: "Tlačiť",
      RateUser: "Ohodnotiť používateľa",
      ReportProduct: "Nahlásiť produkt",
      Rate: "Ohodnotiť",
      Cancel: "Zrušiť",
      RatingTitle: "Názov hodnotenia",
      Title: "Názov",
      RatedBy: "Hodnotené používateľom",
      SelectRating: "Vyber hodnotenie",
      RatedUser: "Hodnotený používateľ",
      RatedProduct: "Hodnotený produkt",
      Description: "Popis",
      User: "Používateľ",
      Product: "Produkt",
      ReportDescription: "Popis problému",
      Report: "Nahlásiť",
      ProductHistory: "História produktu",
      CreatedAt: "Vytvorené",
      SaleEnded: "Predaj skončil",
      NoHistoryInfo: "Tento produkt ešte nemal žiadne významenjšie zmeny!", // This product didn't have any significant changes made yet!
      View: "Zobraziť",
      Sold: "Predané",
      Added: "Pridané",
      ChangedPrice: "Zmena ceny",
      CountOfLeft: "Počet dostupných", // Count of available left
      EditProduct: "Upraviť produkt",
      CreateProduct: "Vytvoriť produkt",
      Preview: "Náhľad",
      Editor: "Úprava",
      Create: "Vytvoriť",
      Save: "Uložiť",
      Sales: "Predaje",
      Images: "Obrázky",
      Main: "Hlavný",
      AddImage: "Pridať obrázok",
      Category: "Kategória",
      SubCategory: "Podkategória",
      Or: "Alebo",
      SpecialPrice: "Špeciálna cena",
      SameAddressInfo: "Použiť rovnakú adresu ako na profile", // Use the same address as your account
      Address: "Adresa",
      Dorm: "Internát",
      NoSalesInfo: "Tento produkt ešte nebol predaný!", // This product doesn't have any sales yet! :(
      Bought: "Kúpil/a",
      Buyer: "Kupujúci",
      Add: "Pridať",
      EditSale: "Upraviť predaj",
      AddSale: "Predať",
      JoinedOn: "Registrovaný/a",
      Rating: "Hodnotenie",
      Products: "Produkty",
      OnSale: "na predaj",
      Ratings: "Hodnotenia",
      ReportUser: "Nahlásiť používateľa",
      onSale: "Na predaj",
      saleEnded: "Predaj skončil",
      self: "Vlastné",
      others: "Ostatné",
      PhoneNumber: "Tel. číslo",
      UserSettings: "Nastavenia požívateľa",
      CisloPlaceholder: "tel. číslo",
      HladajKrajinu: "hľadaj krajinu",
      System: "Systém",
      Messages: "Správy",
      Confirm: "Potvrdiť",
      NoNotiInfo: "Žiadne notifikácie na zobrazenie!", // Seems like there are no notifications for you yet!
      Requests: "Žiadosti",
      NoReqInfo: "Žiadne žiadosti!", // No requests yet!
      Known: "Známe",
      You: "Ty",
      SoEmpty: "... tak prázdno :(", // ... so empty :(
      NoMsgsInfo1: "Zatiaľ tu nie sú žiadne správy!", // Seems like there are no messages yet!  
      NoMsgsInfo2: "Buď prvý čo sa ozve s pozdravom :)", // Be the first one to say hi :)
      SelectChatInfo: "Zvoľ si používateľa pre posielanie a zobrazovanie správ", // Select a chat to send & view messages
      AcceptReqInfo: "Prijmi túto žiadosť aby si mohol písať", // Accept this request to start messaging with user
      Accept: "Prijať",
      AddUserToChat: "Pridať používateľa do chatu",
      Users: "Používatelia",
      Reports: "Nahlásenia",
      all: "Všetko",
      users: "Používatelia",
      products: "Produkty",
      confirmed: "Potvrdené",
      unconfirmed: "Nepotvrdené",
      active: "Aktívny",
      banned: "Banned",
      Rated: "Hodnotil/a",
      Others: "ostatných",
      Own: "vlastné",
      Ban: "Ban",
      Edit: "Upraviť",
      UserAdminEditInfo1: "Ostatné nastavenia sú priamo v", // Other settings are available directly in 
      UserAdminEditInfo2: "požívateľskom profile", // user profile
      DelAvatarInfo: "Vymazať profilovku", // Delete user avatar
      IsSaleConfInfo: "Je predaj potvrdený", // Is sale confirmed
    },
    en: {
      Menu: "Menu",
      AllProducts: "All products",
      Back: "Back",
      Search: "Search",
      AllCategories: "All categories",
      Price: "Price",
      Anywhere: "Anywhere",
      ctg_clothing: "Clothing",
      ctg_footwear: "Footwear",
      ctg_accessories: "Accessories",
      ctg_shirts: "Shirts",
      ctg_tickets: "Tickets",
      ctg_festivals: "Festivals",
      ctg_planeTickets: "Plane tickets",
      ctg_services: "Services",
      ctg_tutoring: "Tutoring",
      ctg_accomodation: "Accomodation",
      ctg_music: "Music",
      ctg_drums: "Drums",
      ctg_guitar: "Guitars",
      ctg_keyboard: "Keyboard",
      ctg_pcPhone: "PC & phone",
      ctg_laptops: "Laptops",
      ctg_pcKeyboard: "Keyboards",
      ctg_mouse: "PC mouses",
      ctg_furniture: "Furniture",
      ctg_chairs: "Chairs",
      ctg_tables: "Tables",
      ctg_drawers: "Drawers",
      ctg_books: "Books",
      ctg_fiction: "Fiction",
      ctg_historical: "Historical",
      ctg_textbooks: "Textbooks",
      ctg_homemade: "Homemade",
      ctg_electronics: "Electronics",
      ctg_microwaves: "Microwaves",
      ctg_refrigerators: "Refrigerators",
      fltr_latest: "Latest",
      fltr_oldest: "Oldes",
      fltr_minPrice: "Smallest price",
      fltr_maxPrice: "Highest price",
      fltr_agreement: "Agreement",
      fltr_offer: "Offer",
      fltr_inText: "In text",
      fltr_free: "Free",
      fltr_userId: "User ID",
      fltr_maxRating: "Biggest ratings",
      fltr_minRating: "Smallest ratings",
      fltr_maxProductsOnSale: "Most products on sale",
      fltr_maxProductsSold: "Most sold products",
      fltr_maxProductsBought: "Most bought products",
      fltr_maxOwnReports: "Most own reports",
      fltr_maxOthersReports: "Most others reports",
      Logout: "Logout",
      Home: "Home",
      Browse: "Browse",
      Favourites: "Favourites",
      MyProducts: "My products",
      Chat: "Chat",
      Login: "Login",
      DoLogin: "Login",
      SignUp: "Sign up",
      DoSignUp: "Sign up",
      AdminPanel: "Admin Panel",
      Notifications: "Notifications",
      CustomerService: "Customer service",
      Terms: "Terms",
      Collaboration: "Collaboration",
      AboutUs: "About us",
      DataPrivacy: "Data privacy",
      FooterCopy: "All rights reserved",
      MadeBy: "Made by",
      AreYouSure: "Are you sure",
      Yes: "Yes",
      No: "No",
      Username: "Username",
      Email: "Email",
      Password: "Password",
      RepeatPassword: "Password again",
      AuthNoAccInfo: "Don't have an account yet?",
      AuthHasAccInfo: "Already have an account?",
      InvalidEmail: "Invalid email",
      InvalidPassword: "Invalid password",
      InvalidUsername: "Invalid username",
      PasswordsDontMatch: "Passwords do not match",
      RegisterSuccess: "Registered successfully",
      RegisterFailed: "Failed to register",
      LoginSuccess: "Login was successfull",
      LoginFailed: "Failed to login",
      BannerUserInfo: "User is banned, reason:",
      InvalidCredentials: "Invalid login credentials",
      ProductsSold: "Products sold",
      SoldIn96hInfo: "products sold in last 96 hours", 
      FAQInfo: "frequently asked questions",
      NotiInfo: "stay up to date",
      LatestSoldProducts: "Latest sold products",
      NoProductsFound: "No products were found! :(",
      agreement: "Agreement",
      offer: "Offer",
      inText: "In text",
      free: "Free",
      ProductTitle: "Product title",
      Location: "Location",
      Views: "Views",
      Count: "Count",
      Message: "Message",
      Seller: "Seller",
      Share: "Share",
      Print: "Print",
      RateUser: "Rate User",
      ReportProduct: "Report Product",
      Rate: "Rate",
      Cancel: "Cancel",
      RatingTitle: "Rating title",
      Title: "Title",
      RatedBy: "Rated by",
      SelectRating: "select rating",
      RatedUser: "Rated user",
      RatedProduct: "Rated product",
      Description: "Description",
      User: "User",
      Product: "Product",
      ReportDescription: "Problem description",
      Report: "Report",
      ProductHistory: "Product history",
      CreatedAt: "Created at",
      SaleEnded: "Sale ended",
      NoHistoryInfo: "This product didn't have any significant changes made yet!",
      View: "View",
      Sold: "Sold",
      Added: "Added",
      ChangedPrice: "Changed price",
      CountOfLeft: "Count of available left",
      EditProduct: "Edit product",
      CreateProduct: "Create product",
      Preview: "Preview",
      Editor: "Editor",
      Create: "Create",
      Save: "Save",
      Sales: "Sales",
      Images: "Images",
      Main: "Main",
      AddImage: "Add image",
      Category: "Category",
      SubCategory: "Subcategory",
      Or: "Or",
      SpecialPrice: "Special price",
      SameAddressInfo: "Use the same address as your account",
      Address: "Address",
      Dorm: "Dorm",
      NoSalesInfo: "This product doesn't have any sales yet! :(",
      Bought: "Bought",
      Buyer: "Buyer",
      Add: "Add",
      EditSale: "Edit sale",
      AddSale: "Add sale",
      JoinedOn: "Joined on",
      Rating: "Rating",
      Products: "Products",
      OnSale: "on sale",
      Ratings: "Ratings",
      ReportUser: "Report user",
      onSale: "on sale",
      saleEnded: "Sale ended",
      self: "Self",
      others: "Others",
      PhoneNumber: "Phone number",
      UserSettings: "User settings",
      CisloPlaceholder: "Phone number",
      HladajKrajinu: "search country",
      System: "System",
      Messages: "Messages",
      Confirm: "Confirm",
      NoNotiInfo: "Seems like there are no notifications for you yet!",
      Requests: "Requests",
      NoReqInfo: "No requests yet!",
      Known: "Known",
      You: "You",
      SoEmpty: "... so empty :(",
      NoMsgsInfo1: "Seems like there are no messages yet!",
      NoMsgsInfo2: "Be the first one to say hi :)",
      SelectChatInfo: "// Select a chat to send & view messages", 
      AcceptReqInfo: "Accept this request to start messaging with user",
      Accept: "Accept",
      AddUserToChat: "Add user to chat",
      Users: "Users",
      Reports: "Reports",
      all: "All",
      users: "Users",
      products: "Products",
      confirmed: "Confirmed",
      unconfirmed: "Unconfirmed",
      active: "Active",
      banned: "Banned",
      Rated: "Rated",
      Others: "Others",
      Own: "Own",
      Ban: "Ban",
      Edit: "Edit",
      UserAdminEditInfo1: "Other settings are available directly in ",
      UserAdminEditInfo2: "user profile",
      DelAvatarInfo: "Delete user avatar",
      IsSaleConfInfo: "Is sale confirmed",
    },
  },
};

export { i18nOptions };
